/** Site knowledge for Ask Loyalife. Short snippets written from the facts only. */
export interface Snippet {
  id: string;
  title: string;
  text: string;
  href: string;
  anchor?: string;
  keywords: string[];
  followups?: string[];
}

export const KNOWLEDGE: Snippet[] = [
  { id: 'scale', title: 'Scale and uptime', text: 'Loyalife manages 65M+ members and has distributed $5B+ in rewards to date. Platform uptime is 99.99%, SLA backed.', href: '/', anchor: 'proof', keywords: ['members', 'scale', 'uptime', 'sla', 'rewards distributed', 'size', 'how big', 'proof'], followups: ['Which countries do you cover?', 'How fast can we launch?'] },
  { id: 'rewards-network', title: 'Rewards network', text: 'The rewards marketplace has 10M+ options in 30+ categories. Rewards are localized in 150+ countries, with 30+ languages and 55+ currencies.', href: '/', anchor: 'rewards', keywords: ['rewards', 'marketplace', 'catalog', 'categories', 'countries', 'languages', 'currencies', 'options', 'localized', 'region'], followups: ['Which program types can Loyalife run?'] },
  { id: 'speed-cost', title: 'Build versus buy', text: 'Launch to first redemption takes 8 to 12 weeks versus 9 to 12 months for an in house build. An in house build needs 3 to 5 engineers, while Loyalife needs 0 to 1 FTE at steady state. Teams see about 50% fewer marketing tickets. In house builds reach 30 to 50 countries with around 50,000 reward options at best.', href: '/pricing', anchor: 'estimator', keywords: ['build', 'buy', 'in house', 'cost', 'time', 'weeks', 'months', 'engineers', 'fte', 'tickets', 'estimate', 'benchmark', 'launch', 'speed'], followups: ['How does pricing work?', 'What deployment options exist?'] },
  { id: 'programs', title: 'Program types', text: 'Loyalife runs enterprise multi brand, channel, influencer, omnichannel and coalition programs.', href: '/platform', anchor: 'pillars', keywords: ['programs', 'types', 'multi brand', 'channel', 'influencer', 'omnichannel', 'coalition', 'enterprise'], followups: ['Can we run programs separately?'] },
  { id: 'tenancy', title: 'Multi-tenancy', text: 'Each program runs independently under one account. This is multi-tenant by design.', href: '/platform/infrastructure', anchor: 'deployment', keywords: ['multi-tenant', 'tenant', 'tenancy', 'separate', 'independent', 'account', 'brands'], followups: ['What deployment options exist?'] },
  { id: 'mobile', title: 'Member app and WhatsApp bot', text: 'Loyalife offers a white label iOS and Android app. A WhatsApp bot lets members check balance, browse and redeem.', href: '/platform', anchor: 'pillars', keywords: ['app', 'ios', 'android', 'whatsapp', 'bot', 'mobile', 'white label', 'white-label', 'balance', 'redeem', 'member'], followups: ['Which program types can Loyalife run?'] },
  { id: 'deployment', title: 'Deployment', text: 'Loyalife supports on-prem, hybrid and cloud deployment. It supports VPC, Active-Active DR, multi-tenant and white-labelling.', href: '/platform/infrastructure', anchor: 'deployment', keywords: ['deployment', 'on-prem', 'on prem', 'hybrid', 'cloud', 'vpc', 'dr', 'disaster recovery', 'active-active', 'hosting', 'infrastructure', 'white-labelling'], followups: ['How do you protect data?'] },
  { id: 'ai-mcp', title: 'Loyalife AI and MCP', text: 'Loyalife AI drafts and watches. People decide. It uses an on-prem LLM + MCP with tenant-isolated, audited tool-calling. A person approves this before anything goes live.', href: '/platform/ai-mcp', anchor: 'ai-studio', keywords: ['ai', 'artificial intelligence', 'llm', 'mcp', 'assistant', 'tool-calling', 'tool calling', 'drafts', 'model'], followups: ['How do you handle fraud and misuse?'] },
  { id: 'security', title: 'Security and certifications', text: 'Security covers PCI-DSS, SOC 2 Type II, ISO 27001, dual-control, audit and ML fraud.', href: '/platform/security', anchor: 'certs', keywords: ['security', 'pci', 'pci-dss', 'soc 2', 'soc2', 'iso', 'iso 27001', 'certification', 'compliance', 'dual-control', 'audit', 'fraud', 'pack'], followups: ['How do you handle fraud and misuse?'] },
  { id: 'governance', title: 'Governance', text: 'Maker checker approvals cover every change. Loyalife keeps an audit trail and an idempotent, replayable reward ledger. Anomaly detection flags unusual activity. Consent, access and deletion workflows run by channel.', href: '/platform/security', anchor: 'dual-control', keywords: ['governance', 'maker', 'checker', 'approval', 'approvals', 'audit', 'trail', 'ledger', 'replay', 'idempotent', 'anomaly', 'consent', 'deletion', 'access', 'privacy'], followups: ['How do you protect data?'] },
  { id: 'apis', title: 'APIs', text: 'APIs are REST-first. OAuth 2.0 to JWT secures access to members, transactions and points.', href: '/platform/apis', anchor: 'api-explorer', keywords: ['api', 'apis', 'rest', 'oauth', 'jwt', 'developer', 'docs', 'documentation', 'endpoint', 'members', 'transactions', 'points'], followups: ['Which systems does Loyalife integrate with?'] },
  { id: 'integrations', title: 'Integrations', text: 'Integrations include Salesforce, Shopify, HubSpot, MoEngage, Stripe, Twilio, Magento and Microsoft Dynamics.', href: '/platform/apis', anchor: 'integrations', keywords: ['integrations', 'integrate', 'salesforce', 'shopify', 'hubspot', 'moengage', 'stripe', 'twilio', 'magento', 'dynamics', 'crm', 'connect'], followups: ['Tell me about the APIs'] },
  { id: 'customers', title: 'Customers', text: 'Customers include AAT, Access, Al Masraf, Alkem Laboratories, Allied Bank, BNI, Bank BRI, Bank bjb, Bank of Maldives, CBI, Commercial Bank, Danamon, Eastern Bank PLC, Ecobank, Eurogrip, Landco Pacific, Mandiri, Mutual Trust Bank PLC, QIB, Siddhartha Bank, Stanley Black & Decker, Worldia, Ahli Bank, SAPTCO and TBO.com.', href: '/', anchor: 'proof', keywords: ['customers', 'clients', 'who uses', 'logos', 'banks', 'references', 'names'], followups: ['Show me the case studies'] },
  { id: 'pricing', title: 'Pricing', text: 'Pricing is not published on this site. Pricing factors are placeholders: members, programs and markets. Talk to sales for a quote.', href: '/pricing', anchor: 'how-pricing-works', keywords: ['price', 'pricing', 'cost', 'quote', 'plans', 'fee', 'fees', 'how much'], followups: ['How does build versus buy compare?'] },
  { id: 'story-mtb', title: 'Mutual Trust Bank story', text: 'Md Abu Bokar Siddik, Head of Cards at Mutual Trust Bank: “Cardholders are now more motivated to use their cards and earn MRewardz points.”', href: '/resources/case-studies/mutual-trust-bank', keywords: ['mutual trust bank', 'cardholders', 'mrewardz', 'cards', 'bank', 'story', 'case study', 'quote'] },
  { id: 'story-cbi', title: 'CBI story', text: 'Siny Antony Davis, Manager, Cards Portfolio Management at CBI: “…leading to a tremendous improvement in customer engagement.”', href: '/resources/case-studies/cbi', keywords: ['cbi', 'engagement', 'cards', 'bank', 'story', 'case study', 'quote'] },
  { id: 'story-ola', title: 'Ola Energy story', text: 'Motaz Ben Saoud, Corporate Retail Officer at Ola Energy: “We chose Loyalife as our loyalty provider to work with us across 17 countries in Africa.”', href: '/resources/case-studies/ola-energy', keywords: ['ola energy', 'africa', 'fuel', 'energy', '17 countries', 'story', 'case study', 'quote'] },
  { id: 'story-tbo', title: 'TBO Holidays story', text: 'Vijayeta James, Global Sales Effectiveness Leader at TBO Holidays: “We have received tremendous response from agencies, bookers, and suppliers across 14 countries on the ease of use of the platform.”', href: '/resources/case-studies/tbo-holidays', keywords: ['tbo', 'tbo holidays', 'travel', 'agencies', 'bookers', 'suppliers', '14 countries', 'story', 'case study', 'quote'] },
  { id: 'demo', title: 'Book a demo', text: 'Book a demo in two short steps. Step one asks for a work email. Step two asks for name, company, region and program type.', href: '/demo', keywords: ['demo', 'book', 'talk', 'contact', 'sales', 'meeting', 'call'] },
];
